name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Run Commands with a Secret
        env:
          SECRET_VALUE: ${{ secrets.SECRET_VALUE }}
        run: |
          echo "This is a secret value: $SECRET_VALUE"
